[package]
name = "ocrs"
version = "0.5.0"
edition = "2021"
authors = ["Robert Knight"]
description = "OCR engine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/robertknight/ocrs"
repository = "https://github.com/robertknight/ocrs"

[dependencies]
anyhow = "1.0.80"
rayon = "1.7.0"
rten = { version = "0.5.0" }
rten-imageproc = { version = "0.4.0" }
rten-tensor = { version = "0.4.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# nb. When changing this, make sure the version of wasm-bindgen-cli installed
# in CI etc. is in sync.
wasm-bindgen = "0.2.89"

[dev-dependencies]
fastrand = "1.9.0"
lexopt = "0.3.0"
rten-imageio = { version = "0.4.0" }

[lib]
crate-type = ["lib", "cdylib"]
